"""CI result analysis helpers for the Developer agent.

Pure data functions — no @ai_function decorators needed.
"""

from __future__ import annotations

import json


def parse_ci_summary(raw_json: str) -> dict:
    """Safely parse a CI summary.json artifact.

    Returns a structured dict with keys: status, examples, duration_s, errors.
    Returns {"status": "parse_error", "raw": raw_json} on failure.
    """
    try:
        data = json.loads(raw_json)
        return {
            "status": data.get("status", "unknown"),
            "examples": data.get("examples", []),
            "duration_s": data.get("duration_s", 0),
            "errors": data.get("errors", []),
        }
    except Exception:
        return {"status": "parse_error", "raw": raw_json}


def classify_plan_changes(resource_changes: list[dict]) -> dict:
    """Classify Terraform plan resource changes by severity.

    Rules:
    - "delete" or "replace" action  → breaking
    - "create"+"delete" in the same resource (in-place replacement) → breaking
    - "update" → potentially_breaking
    - "create"-only → non_breaking

    Args:
        resource_changes: list of resource change dicts from terraform plan JSON
            (each has at minimum an "actions" list and an "address" string).

    Returns:
        {"breaking": [...], "potentially_breaking": [...], "non_breaking": [...]}
    """
    breaking: list[dict] = []
    potentially_breaking: list[dict] = []
    non_breaking: list[dict] = []

    for change in resource_changes:
        actions: list[str] = change.get("actions", [])
        action_set = set(actions)

        if "delete" in action_set or "replace" in action_set:
            breaking.append(change)
        elif "create" in action_set and "delete" in action_set:
            # create+delete in same resource = replacement
            breaking.append(change)
        elif "update" in action_set:
            potentially_breaking.append(change)
        elif action_set == {"create"}:
            non_breaking.append(change)
        else:
            # no-op or unknown — treat as non_breaking
            non_breaking.append(change)

    return {
        "breaking": breaking,
        "potentially_breaking": potentially_breaking,
        "non_breaking": non_breaking,
    }


def generate_upgrade_md_section(
    plan_changes: list[dict], base_ref: str, head_ref: str
) -> str:
    """Generate a markdown UPGRADE.md section from CI plan diff data.

    Args:
        plan_changes: list of resource change dicts from terraform plan JSON.
        base_ref: the base git ref (old version).
        head_ref: the head git ref (new version).

    Returns:
        A formatted markdown string suitable for inclusion in UPGRADE.md.
    """
    classified = classify_plan_changes(plan_changes)

    lines: list[str] = [
        f"## Upgrade: `{base_ref}` → `{head_ref}`",
        "",
        "<!-- Auto-generated by tf-module-developer-agent CI analysis -->",
        "",
    ]

    # Breaking changes
    lines.append("### Breaking Changes")
    if classified["breaking"]:
        for item in classified["breaking"]:
            address = item.get("address", item.get("type", "unknown"))
            actions = ", ".join(item.get("actions", []))
            lines.append(f"- **`{address}`** — actions: `{actions}`")
    else:
        lines.append("_None detected._")
    lines.append("")

    # Resource replacements (subset of breaking — list explicitly)
    replacements = [
        c for c in classified["breaking"]
        if "replace" in c.get("actions", [])
        or ({"create", "delete"} <= set(c.get("actions", [])))
    ]
    lines.append("### Resource Replacements")
    if replacements:
        for item in replacements:
            address = item.get("address", item.get("type", "unknown"))
            lines.append(f"- `{address}`")
    else:
        lines.append("_None detected._")
    lines.append("")

    # Documentation gaps (potentially breaking without UPGRADE.md coverage —
    # callers should cross-reference against existing docs; listed here as a prompt)
    lines.append("### Documentation Gaps")
    if classified["potentially_breaking"]:
        lines.append(
            "> The following resources have **update** actions that may represent "
            "behaviour changes. Verify each is documented in UPGRADE.md:"
        )
        for item in classified["potentially_breaking"]:
            address = item.get("address", item.get("type", "unknown"))
            lines.append(f"- `{address}`")
    else:
        lines.append("_No undocumented potentially-breaking changes detected._")
    lines.append("")

    return "\n".join(lines)
